/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpensesIndexRouteImport } from './routes/expenses.index'
import { Route as ExpensesNewRouteImport } from './routes/expenses.new'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesNewRoute = ExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/workers': typeof WorkersRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses/': typeof ExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/workers': typeof WorkersRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses': typeof ExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/workers': typeof WorkersRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses/': typeof ExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/login'
    | '/materials'
    | '/reports'
    | '/settings'
    | '/workers'
    | '/expenses/new'
    | '/expenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget'
    | '/login'
    | '/materials'
    | '/reports'
    | '/settings'
    | '/workers'
    | '/expenses/new'
    | '/expenses'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/login'
    | '/materials'
    | '/reports'
    | '/settings'
    | '/workers'
    | '/expenses/new'
    | '/expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRoute
  LoginRoute: typeof LoginRoute
  MaterialsRoute: typeof MaterialsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  WorkersRoute: typeof WorkersRoute
  ExpensesNewRoute: typeof ExpensesNewRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/new': {
      id: '/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof ExpensesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRoute,
  LoginRoute: LoginRoute,
  MaterialsRoute: MaterialsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  WorkersRoute: WorkersRoute,
  ExpensesNewRoute: ExpensesNewRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
